COUNTRY_MAPPING = {
    "AFG": "Afghanistan",
    "ANG": "Angola",
    "AND": "Andorra",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ARU": "Aruba",
    "AUS": "Australia",
    "AUT": "Austria",
    "ALB": "Albania",
    "ALG": "Algeria",
    "ATG": "Antigua and Barbuda",
    "AZE": "Azerbaijan",
    "BAN": "Bangladesh",
    "BDI": "Burundi",
    "BEL": "Belgium",
    "BEN": "Benin",
    "BER": "Bermuda",
    "BHR": "Bahrain",
    "BIH": "Bosnia and Herzegovina",
    "BOE": "Bonaire",
    "BOL": "Bolivia",
    "BRA": "Brazil",
    "BRB": "Barbados",
    "BUL": "Bulgaria",
    "BLR": "Belarus",
    "BFA": "Burkina Faso",
    "CAN": "Canada",
    "CHA": "Chad",
    "CGO": "Congo",
    "CHI": "Chile",
    "CHN": "China",
    "CIV": "Côte d'Ivoire",
    "CMR": "Cameroon",
    "COD": "Congo",
    "COL": "Colombia",
    "COM": "Comoros",
    "CPV": "Cape Verde",
    "CRC": "Costa Rica",
    "CRO": "Croatia",
    "CTA": "Central African Republic",
    "CUB": "Cuba",
    "CUW": "Curaçao",
    "CYP": "Cyprus",
    "CZE": "Czech Republic",
    "DEN": "Denmark",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "ENG": "England",
    "ERI": "Eritrea",
    "EQG": "Equatorial Guinea",
    "ESP": "Spain",
    "EST": "Estonia",
    "FIN": "Finland",
    "FRA": "France",
    "FRO": "Faroe Islands",
    "GUF": "French Guiana",
    "GAB": "Gabon",
    "GAM": "Gambia",
    "GEO": "Georgia",
    "GER": "Germany",
    "GHA": "Ghana",
    "GNB": "Guinea-Bissau",
    "GRN": "Grenada",
    "GRE": "Greece",
    "GLP": "Guadeloupe",
    "GUA": "Guatemala",
    "GUI": "Guinea",
    "GUY": "Guyana",
    "HAI": "Haiti",
    "HON": "Honduras",
    "HUN": "Hungary",
    "IND": "India",
    "IDN": "Indonesia",
    "IRL": "Ireland",
    "IRN": "Iran",
    "IRQ": "Iraq",
    "ITA": "Italy",
    "ISL": "Iceland",
    "ISR": "Israel",
    "JAM": "Jamaica",
    "JPN": "Japan",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KGZ": "Kyrgyzstan",
    "KOR": "South Korea",
    "KSA": "Saudi Arabia",
    "KVX": "Kosovo",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LIE": "Liechtenstein",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "LVA": "Latvia",
    "LAO": "Laos",
    "MAD": "Madagascar",
    "MAR": "Morocco",
    "MAS": "Malaysia",
    "MEX": "Mexico",
    "MLI": "Mali",
    "MLT": "Malta",
    "MNG": "Mongolia",
    "MKD": "North Macedonia",
    "MDA": "Moldova",
    "MNE": "Montenegro",
    "MOZ": "Mozambique",
    "MSR": "Montserrat",
    "MTN": "Mauritania",
    "MTQ": "Martinique",
    "MRI": "Mauritius",
    "NED": "Netherlands",
    "NIR": "Northern Ireland",
    "NGA": "Nigeria",
    "NIG": "Niger",
    "NOR": "Norway",
    "NZL": "New Zealand",
    "NCL": "New Caledonia",
    "PRK": "North Korea",
    "PAR": "Paraguay",
    "PAN": "Panama",
    "PAK": "Pakistan",
    "PER": "Peru",
    "PHI": "Philippines",
    "PLE": "Palestine",
    "POL": "Poland",
    "POR": "Portugal",
    "PUR": "Puerto Rico",
    "QAT": "Qatar",
    "ROU": "Romania",
    "RSA": "South Africa",
    "RUS": "Russia",
    "RWA": "Rwanda",
    "SEN": "Senegal",
    "SCO": "Scotland",
    "SMA": "Sint Maarten",
    "SMN": "San Marino",
    "SKN": "Saint Kitts and Nevis",
    "SLE": "Sierra Leone",
    "SLV": "El Salvador",
    "SRB": "Serbia",
    "STP": "São Tomé and Príncipe",
    "SUR": "Suriname",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SUI": "Switzerland",
    "SWE": "Sweden",
    "SYR": "Syria",
    "TAN": "Tanzania",
    "TCH": "Czech Republic",
    "THA": "Thailand",
    "TKM": "Turkmenistan",
    "TOG": "Togo",
    "TUN": "Tunisia",
    "TRI": "Trinidad and Tobago",
    "TPE": "Chinese Taipei",
    "TUR": "Turkey",
    "UAE": "United Arab Emirates",
    "UKR": "Ukraine",
    "URU": "Uruguay",
    "USA": "United States",
    "UZB": "Uzbekistan",
    "UGA": "Uganda",
    "VIE": "Vietnam",
    "VEN": "Venezuela",
    "WAL": "Wales",
    "ZAM": "Zambia",
    "ZIM": "Zimbabwe",
}

METRIC_MAPPING = {
    "Rk": "rank",
    "MP": "matches_played",
    "W": "wins",
    "D": "draws",
    "L": "losses",
    "GF": "goals_for",
    "GA": "goals_against",
    "GD": "goal_difference",
    "Pts": "points",
    "Pts/MP": "points_per_match_played",
    "xG": "expected_goals",
    "xGA": "expected_goals_against",
    "xGD": "expected_goal_difference",
    "xGD/90": "expected_goal_difference_per_90_minutes",
    "# Pl": "number_of_players_used_in_games",
    "Age": "age",
    "Poss": "possession",
    "Starts": "starts",
    "Min": "minutes_played",
    "90s": "90s_played",
    "Gls": "goals",
    "Ast": "assists",
    "G+A": "goals_and_assists",
    "G-PK": "non_penalty_goals",
    "PK": "penalty_kicks",
    "PKatt": "penalty_kicks_attempted",
    "CrdY": "yellow_cards",
    "CrdR": "red_cards",
    "npxG": "non_penalty_expected_goals",
    "xAG": "expected_assisted_goals",
    "npxG+xAG": "non_penalty_expected_goals_plus_expected_assisted_goals",
    "PrgC": "progressive_carries",
    "PrgP": "progressive_passes",
    "GA90": "goals_against_per_90_minutes",
    "SoTA": "shots_on_target",
    "Saves": "saves",
    "Save%": "save_percentage",
    "CS": "clean_sheets",
    "CS%": "clean_sheets_percentage",
    "PKatt": "penalty_kicks_attempted",
    "PKA": "penalty_kicks_allowed",
    "PKsv": "penalty_kicks_saved",
    "PKm": "penalty_kicks_missed",
    "FK": "free_kicks",
    "CK": "corner_kicks",
    "OG": "own_goals",
}

STATS_MAPPING = {
    "nationality": "nationality",
    "position": "position",
    "age": "age",
    "minutes": "minutes",
    "shirtnumber": "number",
    # summary stats
    "goals": "goals",
    "assists": "assists",
    "pens_made": "penalty_kicks_made",
    "pens_att": "penalty_kicks_attempted",
    "shots": "shots",
    "shots_on_target": "shots_on_target",
    "cards_yellow": "yellow_cards",
    "cards_red": "red_cards",
    "touches": "touches",
    "tackles": "tackles",
    "interceptions": "interceptions",
    "blocks": "blocks",
    "xg": "expected_goals",
    "npxg": "non_penalty_expected_goals",
    "xg_assist": "expected_assisted_goals",
    "sca": "shot_creating_actions",
    "gca": "goal_creating_actions",
    "passes_completed": "passes_completed",
    "passes": "passes",
    "passes_pct": "pass_completion_pct",
    "progressive_passes": "progressive_passes",
    "carries": "carries",
    "progressive_carries": "progressive_carries",
    "take_ons": "take_ons_attempted",
    "take_ons_won": "successful_take_ons",
    # passing stats
    "passes_completed": "passes_completed",
    "passes": "passes_attempted",
    "pass_completion_pct": "pass_completion_pct",
    "passes_total_distance": "passes_total_distance",
    "passes_progressive_distance": "passes_progressive_distance",
    "passes_completed_short": "short_passes_completed",
    "passes_short": "short_passes_attempted",
    "passes_pct_short": "short_passes_completion_pct",
    "passes_completed_medium": "medium_passes_completed",
    "passes_medium": "medium_passes_attempted",
    "passes_pct_medium": "medium_passes_completion_pct",
    "passes_completed_long": "long_passes_completed",
    "passes_long": "long_passes_attempted",
    "passes_pct_long": "long_passes_completion_pct",
    "pass_xa": "expected_assists",
    "assisted_shots": "assisted_shots",
    "passes_into_final_third": "passes_into_final_third",
    "passes_into_penalty_area": "passes_into_penalty_area",
    "crosses_into_penalty_area": "crosses_into_penalty_area",
    # pass type stats
    "passes_live": "live_ball_passes",
    "passes_dead": "dead_ball_passes",
    "passes_free_kicks": "free_kick_passes",
    "through_balls": "through_balls",
    "passes_switches": "switches",
    "crosses": "crosses",
    "throw_ins": "throw_ins",
    "corner_kicks": "corner_kicks",
    "corner_kicks_in": "inswinging_corner_kicks",
    "corner_kicks_out": "outswinging_corner_kicks",
    "conrner_kicks_straight": "straight_corner_kicks",
    "passes_offsides": "passes_offsides",
    "passes_blocked": "passes_blocked",
    # defensive stats
    "tackles_def_3rd": "tackles_in_def_3rd",
    "tackles_mid_3rd": "tackles_in_mid_3rd",
    "tackles_att_3rd": "tackles_in_att_3rd",
    "challenge_tackles": "challenge_tackles",
    "challenges": "challenges",
    "challenge_tackles_pct": "challenge_tackles_pct",
    "challenges_lost": "challenges_lost",
    "blocked_shots": "blocked_shots",
    "blocked_passes": "blocked_passes",
    "tackles_interceptions": "tackles_plus_interceptions",
    "clearances": "clearances",
    "errors": "errors_leading_to_goal",
    # possession stats
    'touches': "touches",
    'touches_def_pen_area': "touches_in_def_penalty_area",
    'touches_def_3rd': "touches_in_def_3rd",
    'touches_mid_3rd': "touches_in_mid_3rd",
    'touches_att_3rd': "touches_in_att_3rd",
    'touches_att_pen_area': "touches_in_att_penalty_area",
    'touches_live_ball': "live_ball_touches",
    'take_ons_attempted': "take_ons_attempted",
    'successful_take_ons': "successful_take_ons",
    'take_ons_won_pct': "successful_take_ons_pct",
    'take_ons_tackled': "take_ons_tackled",
    'take_ons_tackled_pct': "take_ons_tackled_pct",
    'carries': "carries",
    'carries_distance': "total_carrying_distance",
    'carries_progressive_distance': "progressive_carrying_distance",
    'progressive_carries': "progressive_carries",
    'carries_into_final_third': "carries_into_final_third",
    'carries_into_penalty_area': "carries_into_penalty_area",
    'miscontrols': "miscontrols",
    'dispossessed': "dispossessed",
    'passes_received': "passes_received",
    'progressive_passes_received': "progressive_passes_received",
    # miscellaneous stats
    'cards_yellow_red': 'second_yellow_cards',
    'fouls': 'fouls_committed',
    'fouled': 'fouls_drawn',
    'offsides': 'offsides',
    'crosses': 'crosses',
    'interceptions': 'interceptions',
    'tackles_won': 'tackles_won',
    'pens_won': 'penalty_kicks_won',
    'pens_conceded': 'penalty_kicks_conceded',
    'own_goals': 'own_goals',
    'ball_recoveries': 'ball_recoveries',
    'aerials_won': 'aerials_won',
    'aerials_lost': 'aerials_lost',
    'aerials_won_pct': 'aerials_won_pct',
    # goalkeeper stats
    "gk_shots_on_target_against": "shots_on_target_against",
    "gk_goals_against": "goals_against",
    "gk_saves": "saves",
    "gk_save_pct": "save_percentage",
    "gk_psxg": "post_shot_expected_goals",
    "gk_passes_completed_launched": "launched_passes_completed",
    "gk_passes_launched": "launched_passes_attempted",
    "gk_passes_pct_launched": "launched_passes_completion_pct",
    "gk_passes": "passes_attempted",
    "gk_passes_throws": "throws_attempted",
    "gk_pct_passes_launched": "launch_percentage",
    "gk_passes_length_avg": "average_pass_length",
    "gk_goal_kicks": "goal_kicks_attempted",
    "gk_pct_goal_kicks_launched": "goal_kicks_launch_percentage",
    "gk_goal_kick_length_avg": "average_goal_kick_length",
    "gk_crosses": "crosses_faced",
    "gk_crosses_stopped": "crosses_stopped",
    "gk_crosses_stopped_pct": "crosses_stopped_percentage",
    "gk_def_actions_outside_pen_area": "defensive_actions_outside_penalty_area",
    "gk_avg_distance_def_actions": "average_distance_defensive_actions",
}


LEADER_TABLE_TYPE_MAPPING = {
    # Format: "key": ("div_id_for_parsing", "schema_table_name")
    # attack metrics
    "goals": ("leaders_goals", "leaders_goals_tables"),
    "goals_per90": ("leaders_goals_per90", "leaders_goals_per90_tables"),
    "assists": ("leaders_assists", "leaders_assists_tables"),
    "assists_per90": ("leaders_assists_per90", "leaders_assists_per90_tables"),
    "goals_plus_assists": ("leaders_goals_assists", "leaders_goals_assists_tables"),
    "goals_plus_assists_per90": ("leaders_goals_assists_per90", "leaders_goals_assists_per90_tables"),
    "penalty_kicks_made": ("leaders_pens_made", "leaders_penalty_kicks_made_tables"),
    "non_penalty_goals": ("leaders_goals_pens", "leaders_non_penalty_goals_tables"),
    "expected_goals": ("leaders_xg", "leaders_expected_goals_tables"),
    "expected_goals_per90": ("leaders_xg_per90", "leaders_expected_goals_per90_tables"),
    "expected_goals_non_penalty": ("leaders_npxg", "leaders_expected_goals_non_penalty_tables"),
    "expected_goals_non_penalty_per90": ("leaders_npxg_per90", "leaders_expected_goals_non_penalty_per90_tables"),
    "expected_assisted_goals": ("leaders_xg_assist", "leaders_expected_assisted_goals_tables"),
    "expected_assisted_goals_per90": ("leaders_xg_assist_per90", "leaders_expected_assisted_goals_per90_tables"),
    "shots": ("leaders_shots", "leaders_shots_tables"),
    "shots_per90": ("leaders_shots_per90", "leaders_shots_per90_tables"),
    "shots_on_target": ("leaders_shots_on_target", "leaders_shots_on_target_tables"),
    "shots_on_target_per90": ("leaders_shots_on_target_per90", "leaders_shots_on_target_per90_tables"),
    "shots_on_target_pct": ("leaders_shots_on_target_pct", "leaders_shots_on_target_pct_tables"),
    "goals_per_shot": ("leaders_goals_per_shot", "leaders_goals_per_shot_tables"),
    "goals_per_shot_on_target": ("leaders_goals_per_shot_on_target", "leaders_goals_per_shot_on_target_tables"),
    "expected_goals_non_penalty_per_shot": ("leaders_npxg_per_shot", "leaders_expected_goals_non_penalty_per_shot_tables"),
    "goals_minus_expected_goals": ("leaders_xg_net", "leaders_goals_minus_expected_goals_tables"),
    "non_penalty_goals_minus_expected_goals": ("leaders_npxg_net", "leaders_non_penalty_goals_minus_expected_goals_tables"),
    # passing metrics
    "leaders_key_passes": ("leaders_assisted_shots", "leaders_key_passes_tables"),
    "pass_completion_pct": ("leaders_passes_pct", "leaders_pass_completion_pct_tables"),
    "progressive_passing_distance": ("leaders_passes_progressive_distance", "leaders_progressive_passing_distance_tables"),
    "passes_into_final_third": ("leaders_passes_into_final_third", "leaders_passes_into_final_third_tables"),
    "passes_into_penalty_area": ("leaders_passes_into_penalty_area", "leaders_passes_into_penalty_area_tables"),
    "crosses_into_penalty_area": ("leaders_crosses_into_penalty_area", "leaders_crosses_into_penalty_area_tables"),
    "progressive_passes": ("leaders_progressive_passes", "leaders_progressive_passes_tables"),
    "through_balls": ("leaders_through_balls", "leaders_through_balls_tables"),
    "expected_assists": ("leaders_pass_xa", "leaders_expected_assists_tables"),
    "expected_assists_per90": ("leaders_pass_xa_per90", "leaders_expected_assists_per90_tables"),
    "corner_kicks": ("leaders_corner_kicks", "leaders_corner_kicks_tables"),
    "crosses": ("leaders_crosses", "leaders_crosses_tables"),
    "throw_ins_taken": ("leaders_throw_ins", "leaders_throw_ins_tables"),
    "shot_creating_actions": ("leaders_sca", "leaders_shot_creating_actions_tables"),
    "shot_creating_actions_per90": ("leaders_sca_per90", "leaders_shot_creating_actions_per90_tables"),
    "goal_creating_actions": ("leaders_gca", "leaders_goal_creating_actions_tables"),
    "goal_creating_actions_per90": ("leaders_gca_per90", "leaders_goal_creating_actions_per90_tables"),
    # possession metrics
    "touches": ("leaders_touches", "leaders_touches_tables"),
    "successful_take_ons": ("leaders_take_ons_won", "leaders_successful_take_ons_tables"),
    "successful_take_ons_pct": ("leaders_take_ons_won_pct", "leaders_successful_take_ons_pct_tables"),
    "progressive_carriying_distance": ("leaders_carries_progressive_distance", "leaders_progressive_carriying_distance_tables"),
    "progressive_carries": ("leaders_progressive_carries", "leaders_progressive_carries_tables"),
    "carries_into_penalty_area": ("leaders_carries_into_penalty_area", "leaders_carries_into_penalty_area_tables"),
    "progressive_passes_received": ("leaders_progressive_passes_received", "leaders_progressive_passes_received_tables"),
    # defensive metrics
    "blocks": ("leaders_blocks", "leaders_blocks_tables"),
    "interceptions": ("leaders_interceptions", "leaders_interceptions_tables"),
    "clearances": ("leaders_clearances", "leaders_clearances_tables"),
    "aerials_won": ("leaders_aerials_won", "leaders_aerials_won_tables"),
    "aerials_won_pct": ("leaders_aerials_won_pct", "leaders_aerials_won_pct_tables"),
    "tackles": ("leaders_tackles", "leaders_tackles_tables"),
    "tackles_won": ("leaders_tackles_won", "leaders_tackles_won_tables"),
    "dirbblers_tacked": ("leaders_challenge_tackles", "leaders_dirbblers_tacked_tables"),
    "dirbblers_tacked_pct": ("leaders_challenge_tackles_pct", "leaders_dirbblers_tacked_pct_tables"),
    "own_goals": ("leaders_own_goals", "leaders_own_goals_tables"),
    # disciplinary metrics
    "yellow_cards": ("leaders_cards_yellow", "leaders_yellow_cards_tables"),
    "red_cards": ("leaders_cards_red", "leaders_red_cards_tables"),
    "fouls_committed": ("leaders_fouls", "leaders_fouls_committed_tables"),
    "fouls_drawn": ("leaders_fouled", "leaders_fouls_drawn_tables"),
    # goalkeeper metrics
    "clean_sheets": ("leaders_gk_clean_sheets", "leaders_clean_sheets_tables"),
    "clean_sheets_pct": ("leaders_gk_clean_sheets_pct", "leaders_clean_sheets_pct_tables"),
    "saves": ("leaders_gk_saves", "leaders_saves_tables"),
    "saves_pct": ("leaders_gk_save_pct", "leaders_saves_pct_tables"),
    "goals_against_per90": ("leaders_gk_goals_against_per90", "leaders_goals_against_per90_tables"),
    "post_shot_expected_goals_minus_goals_against": ("leaders_gk_psxg_net", "leaders_post_shot_expected_goals_minus_goals_against_tables"),
    "post_shot_expected_goals_minus_goals_against_per90": ("leaders_gk_psxg_net_per90", "leaders_post_shot_expected_goals_minus_goals_against_per90_tables"),
    # other metrics
    "minutes": ("leaders_minutes", "leaders_minutes_tables"),
    "substitute_appearances": ("leaders_games_subs", "leaders_substitute_appearances_tables"),
    "points_per_match": ("leaders_points_per_game", "leaders_points_per_match_tables"),
    "plus_minus": ("leaders_plus_minus", "leaders_plus_minus_tables"),
    "plus_minus_per90": ("leaders_plus_minus_per90", "leaders_plus_minus_per90_tables"),
    "xg_plus_minus": ("leaders_xg_plus_minus", "leaders_xg_plus_minus_tables"),
    "xg_plus_minus_per90": ("leaders_xg_plus_minus_per90", "leaders_xg_plus_minus_per90_tables"),
}